// <auto-generated />
using System;
using CVWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace CVWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CVWebsite.Models.PendingPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Fulfilled");

                    b.Property<long>("OrderCode");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode").IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PendingPayments");
                });

            modelBuilder.Entity("CVWebsite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("PlanActivatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Email").IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CVWebsite.Models.PendingPayment", b =>
                {
                    b.HasOne("CVWebsite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
